### ISSUE TITLE
Khong noi Tieng Viet duoc

### ISSUE THREAD

**Issue by vietnq2004** [phanmemkhoinghiep/google_assistant_vietnamese_speaking#2]

**Comment by vietnq2004** [comment]
Minh chay theo lenh nay python3 register_device.py --project-id <ten_project> --device-model-id <ten_device_id>

Nhan enter roi noi OK google

Minh noi tieng viet nhung no khong hieu
Chi hieu tieng ANh

Nho ban giup nhe

Chao
Viet

**Comment by quangvinh9x** [comment]
Đồng chí đã thay ten project vs ten device vào chưa

**Comment by vietnq2004** [comment]
da thay roi ban. minh tao file json cua minh

**Comment by vietnq2004** [comment]
python3 start.py
pygame 1.9.4.post1
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "start.py", line 2, in <module>
    import pushtotalk
  File "pushtotalk.py", line 24, in init pushtotalk
FileNotFoundError: [Errno 2] No such file or directory: 'config.json'

Loi nay sao vay ban
Giup minh nhe

Viet

**Comment by vietnq2004** [comment]
Minhsu dung ReSpeaker 2-Mics Pi HAT 
Khi cai img cua ban minh kiem tra arecord -l thi khong thay mic
Minh cai driver lai theo sudo apt-get update
git clone https://github.com/respeaker/seeed-voicecard.git
cd seeed-voicecard
sudo ./install.sh
sudo reboot now
thi co mic
minh edit python3 create_config.py 
data['mic'].append({
    'type': 'ReSpeaker 2/4-Mics Pi HAT',
    'is_active': True  
may cai khac false

Minh Chay  python3 start.py
no hien ra 
pygame 1.9.4.post1
Hello from the pygame community. https://www.pygame.org/contribute.html
INFO:root:Connecting to embeddedassistant.googleapis.com
INFO:root:Using device model dh-assistant-98bc5-loa-tv-5rb5il and device id 6b5337fe-1db4-11ec-985a-b827eb7f6a80

Minh noi OK google hey google hi siri 

Nhung ko co phan hoi

Minh co lam sai gi khong vay ban

Cam on
Viet
